package com.freevisiontech.fvmobile.model.resolver;

import android.util.SparseArray;

public class CompanyIdentifierResolver {
    public static final int AAMP_OF_AMERICA = 190;
    public static final int ABOVE_AVERAGE_OUTCOMES_INC = 238;
    public static final int ACCEL_SEMICONDUCTOR_LTD = 74;
    public static final int ACEUNI_CORP_LTD = 248;
    public static final int ACE_SENSOR_INC = 188;
    public static final int ACTS_TECHNOLOGIES = 232;
    public static final int ADIDAS_AG = 195;
    public static final int ADVANCED_PANMOBIL_SYSTEMS_GMBH_CO_KG = 145;
    public static final int AD_ENGINEERING_INC = 105;
    public static final int AIREWEAR_LLC = 309;
    public static final int AIROHA_TECHNOLOGY_CORP = 148;
    public static final int AIRTURN_INC = 290;
    public static final int ALCATEL = 36;
    public static final int ALPWISE = 154;
    public static final int AMICCOM_ELECTRONICS_CORPORATION = 192;
    public static final int APLIX_CORPORATION = 189;
    public static final int APPLE_INC = 76;
    public static final int APT_LICENSING_LTD = 79;
    public static final int ARCHOS_SA = 207;
    public static final int ARENDI_AG = 285;
    public static final int ARP_DEVICES_LIMITED = 168;
    public static final int ARUBA_NETWORKS = 283;
    public static final int ASSA_ABLOY = 302;
    public static final int ATHEROS_COMMUNICATIONS_INC = 69;
    public static final int ATMEL_CORPORATION = 19;
    public static final int ATUS_BV = 265;
    public static final int AUDI_AG = 270;
    public static final int AUSTCO_COMMUNICATION_SYSTEMS = 213;
    public static final int AUTONET_MOBILE = 127;
    public static final int AVAGO_TECHNOLOGIES = 78;
    public static final int AVM_BERLIN = 31;
    public static final int A_R_CAMBRIDGE = 124;
    public static final int BAIDU = 284;
    public static final int BANDSPEED_INC = 32;
    public static final int BAND_XI_INTERNATIONAL_LLC = 100;
    public static final int BANG_OLUFSEN_A_S = 259;
    public static final int BDE_TECHNOLOGY_CO_LTD = 180;
    public static final int BEATS_ELECTRONICS = 204;
    public static final int BEAUTIFUL_ENTERPRISE_CO_LTD = 108;
    public static final int BEKEY_A_S = 178;
    public static final int BELKIN_INTERNATIONAL_INC = 92;
    public static final int BINAURIC_SE = 203;
    public static final int BIORESEARCH_ASSOCIATES = 236;
    public static final int BIOSENTRONICS = 219;
    public static final int BITSPLITTERS_GMBH = 239;
    public static final int BLUEGIGA = 71;
    public static final int BLUERADIOS_INC = 133;
    public static final int BLUETOOTH_SIG_INC = 63;
    public static final int BLUE_MAESTRO_LIMITED = 307;
    public static final int BOSE_CORPORATION = 158;
    public static final int BRIARTEK_INC = 109;
    public static final int BROADCOM_CORPORATION = 15;
    public static final int CAEN_RFID_SRL = 170;
    public static final int CAMBRIDGE_SILICON_RADIO = 10;
    public static final int CEVA_INC_FORMERLY_PARTHUS_TECHNOLOGIES_INC = 14;
    public static final int CHANGZHOU_YONGSE_INFOTECH_CO_LTD = 298;
    public static final int CHICONY_ELECTRONICS_CO_LTD = 264;
    public static final int CINETIX = 175;
    public static final int CLARINOX_TECHNOLOGIES_PTY_LTD = 179;
    public static final int CLARION_CO_LTD = 303;
    public static final int CODEGATE_LTD = 266;
    public static final int COLORFY_INC = 156;
    public static final int COMMIL_LTD = 51;
    private static final SparseArray<String> COMPANY_NAME_MAP = populateCompanyNameMap();
    public static final int COMPUTER_ACCESS_TECHNOLOGY_CORPORATION_CATC = 52;
    public static final int CONEXANT_SYSTEMS_INC = 28;
    public static final int CONNECTBLUE_AB = 113;
    public static final int CONNECTEDEVICE_LTD = 151;
    public static final int CONTINENTAL_AUTOMOTIVE_SYSTEMS = 75;
    public static final int CONWISE_TECHNOLOGY_CORPORATION_LTD = 66;
    public static final int CREATIVE_TECHNOLOGY_LTD = 118;
    public static final int CRYSTAL_CODE_AB = 250;
    public static final int CYPRESS_SEMICONDUCTOR_CORPORATION = 305;
    public static final int C_TECHNOLOGIES = 38;
    public static final int DANLERS_LTD = 225;
    public static final int DELORME_PUBLISHING_COMPANY_INC = 128;
    public static final int DELPHI_CORPORATION = 252;
    public static final int DEXCOM_INC = 208;
    public static final int DIALOG_SEMICONDUCTOR_BV = 210;
    public static final int DIGIANSWER_A_S = 12;
    public static final int ECLIPSE_HQ_ESPANA_SL = 53;
    public static final int ECOTEST = 136;
    public static final int EDEN_SOFTWARE_CONSULTANTS_LTD = 229;
    public static final int ELCOMETER_LIMITED = 246;
    public static final int ELGATO_SYSTEMS_GMBH = 206;
    public static final int EM_MICROELECTRONICMARIN_SA = 90;
    public static final int EQUINOX_AG = 134;
    public static final int ERICSSON_TECHNOLOGY_LICENSING = 0;
    public static final int ERI_INC = 267;
    public static final int ESOLUTIONS = 277;
    public static final int ETC_SP_ZOO = 310;
    public static final int EVLUMA = 201;
    public static final int FREE2MOVE_AB = 83;
    public static final int FRESHTEMP = 230;
    public static final int FUGOO_INC = 257;
    public static final int FUJITSU_TEN_LIMITED = 269;
    public static final int FUNAI_ELECTRIC_CO_LTD = 144;
    public static final int GARMIN_INTERNATIONAL_INC = 135;
    public static final int GCT_SEMICONDUCTOR = 45;
    public static final int GELO_INC = 200;
    public static final int GENEQ_INC = 194;
    public static final int GENERAL_MOTORS = 104;
    public static final int GENNUM_CORPORATION = 59;
    public static final int GEOFORCE_INC = 157;
    public static final int GIBSON_GUITARS = 98;
    public static final int GN_NETCOM_A_S = 103;
    public static final int GN_RESOUND_A_S = 137;
    public static final int GOOGLE = 224;
    public static final int GPSI_GROUP_PTY_LTD = 296;
    public static final int GREEN_THROTTLE_GAMES = 172;
    public static final int GROUP_SENSE_LTD = 115;
    public static final int HANLYNN_TECHNOLOGIES = 123;
    public static final int HARMAN_INTERNATIONAL_INDUSTRIES_INC = 87;
    public static final int HEWLETTPACKARD_COMPANY = 101;
    public static final int HID_GLOBAL = 292;
    public static final int HISILICON_TECHNOLOGIES_CO_LTD = 271;
    public static final int HITACHI_LTD = 41;
    public static final int HOSIDEN_CORPORATION = 221;
    public static final int IBM_CORP = 3;
    public static final int INFINEON_TECHNOLOGIES_AG = 9;
    public static final int INGENIEURSYSTEMGRUPPE_ZAHN_GMBH = 171;
    public static final int INMUSIC_BRANDS_INC = 227;
    public static final int INNOVATIVE_YACHTTER_SOLUTIONS = 262;
    public static final int INTEGRATED_SILICON_SOLUTION_TAIWAN_INC = 65;
    public static final int INTEGRATED_SYSTEM_SOLUTION_CORP = 57;
    public static final int INTEL_CORP = 2;
    public static final int INVENTEL = 30;
    public static final int IPEXTREME_INC = 61;
    public static final int ITECH_DYNAMIC_GLOBAL_DISTRIBUTION_LTD = 153;
    public static final int JAWBONE = 138;
    public static final int JIANGSU_TOPPOWER_AUTOMOTIVE_ELECTRONICS_CO_LTD = 155;
    public static final int JM_CORPORATION = 82;
    public static final int JOHNSON_CONTROLS_INC = 185;
    public static final int JOLLY_LOGIC_LLC = 237;
    public static final int KAWANTECH = 212;
    public static final int KC_TECHNOLOGY_INC = 22;
    public static final int KEISER_CORPORATION = 258;
    public static final int KENSINGTON_COMPUTER_PRODUCTS_GROUP = 160;
    public static final int KENT_DISPLAYS_INC = 243;
    public static final int KINSA_INC = 291;
    public static final int KOUKAAM_AS = 251;
    public static final int KS_TECHNOLOGIES = 231;
    public static final int LAIRD_TECHNOLOGIES = 119;
    public static final int LESSWIRE_AG = 121;
    public static final int LG_ELECTRONICS = 196;
    public static final int LINAK_A_S = 164;
    public static final int LS_RESEARCH_INC = 228;
    public static final int LUCENT = 7;
    public static final int LUDUS_HELSINKI_LTD = 132;
    public static final int MACRONIX_INTERNATIONAL_CO_LTD = 44;
    public static final int MADS_INC = 306;
    public static final int MAGNETI_MARELLI_SPA = 169;
    public static final int MANSELLA_LTD = 33;
    public static final int MARVELL_TECHNOLOGY_GROUP_LTD = 72;
    public static final int MATSUSHITA_ELECTRIC_INDUSTRIAL_CO_LTD = 58;
    public static final int MC10 = 202;
    public static final int MEDIATEK_INC = 70;
    public static final int MESO_INTERNATIONAL = 182;
    public static final int META_WATCH_LTD = 163;
    public static final int MEWTEL_TECHNOLOGY_INC = 47;
    public static final int MICOMMAND_INC = 99;
    public static final int MICROCHIP_TECHNOLOGY_INC = 205;
    public static final int MICROSOFT = 6;
    public static final int MINDTREE_LTD = 106;
    public static final int MISFIT_WEARABLES_CORP = 223;
    public static final int MITEL_SEMICONDUCTOR = 16;
    public static final int MITSUBISHI_ELECTRIC_CORPORATION = 20;
    public static final int MOBILIAN_CORPORATION = 55;
    public static final int MONSTER_LLC = 112;
    public static final int MORSE_PROJECT_INC = 242;
    public static final int MOTOROLA = 8;
    public static final int MSTAR_SEMICONDUCTOR_INC = 122;
    public static final int MUZIK_LLC = 222;
    public static final int NAUTILUS_INC = 244;
    public static final int NEC_CORPORATION = 34;
    public static final int NEC_LIGHTING_LTD = 149;
    public static final int NEWLOGIC = 23;
    public static final int NIELSENKELLERMAN_COMPANY = 234;
    public static final int NIKE_INC = 120;
    public static final int NIMBLE_DEVICES_OY = 297;
    public static final int NINE_SOLUTIONS_OY = 102;
    public static final int NIPPON_SEIKI_CO_LTD = 272;
    public static final int NOKIA_MOBILE_PHONES = 1;
    public static final int NORDIC_SEMICONDUCTOR_ASA = 89;
    public static final int NORWOOD_SYSTEMS = 46;
    public static final int ODM_TECHNOLOGY_INC = 150;
    public static final int OMEGAWAVE_OY = 174;
    public static final int ONE_OAK_TECHNOLOGIES = 278;
    public static final int ONSET_COMPUTER_CORPORATION = 197;
    public static final int OPENBRAIN_TECHNOLOGIES_CO_LTD = 275;
    public static final int OPEN_INTERFACE = 39;
    public static final int OTL_DYNAMICS_LLC = 165;
    public static final int PANDA_OCEAN_INC = 166;
    public static final int PARROT_SA = 67;
    public static final int PASSIF_SEMICONDUCTOR_CORP = 176;
    public static final int PAYPAL_INC = 240;
    public static final int PETER_SYSTEMTECHNIK_GMBH = 173;
    public static final int PHILIPS_SEMICONDUCTORS = 37;
    public static final int PLANTRONICS_INC = 85;
    public static final int PLUS_LOCATIONS_SYSTEMS_PTY_LTD = 260;
    public static final int POLAR_ELECTRO_EUROPE_BV = 209;
    public static final int POLAR_ELECTRO_OY = 107;
    public static final int PORSCHE_AG = 288;
    public static final int PRESTIGIO_PLAZA_LTD = 311;
    public static final int PROCTER_GAMBLE = 220;
    public static final int PROMETHEAN_LTD = 294;
    public static final int QUALCOMM = 29;
    public static final int QUALCOMM_CONNECTED_EXPERIENCES_INC = 216;
    public static final int QUALCOMM_INNOVATION_CENTER_INC_QUIC = 184;
    public static final int QUALCOMM_LABS_INC = 282;
    public static final int QUALCOMM_RETAIL_SOLUTIONS_INC_FORMERLY_QUALCOMM_LABS_INC = 140;
    public static final int QUALCOMM_TECHNOLOGIES_INC = 215;
    public static final int QUINTIC_CORP = 142;
    public static final int QUUPPA_OY = 199;
    public static final int RADIUS_NETWORKS_INC = 280;
    public static final int RALINK_TECHNOLOGY_CORPORATION = 91;
    public static final int RDA_MICROELECTRONICS = 97;
    public static final int REALTEK_SEMICONDUCTOR_CORPORATION = 93;
    public static final int REDM_COMMUNICATIONS_LTD = 50;
    public static final int RENESAS_TECHNOLOGY_CORP = 54;
    public static final int RESEARCH_IN_MOTION = 60;
    public static final int RESERVED = 254;
    public static final int RESOLUTION_PRODUCTS_INC = 308;
    public static final int RIVIERAWAVES_SAS = 96;
    public static final int ROHDE_SCHWARZ_GMBH_CO_KG = 25;
    public static final int RTX_TELECOM_A_S = 21;
    public static final int R_F_MICRO_DEVICES = 40;
    public static final int SALUTICA_ALLIED_SOLUTIONS = 295;
    public static final int SAMSUNG_ELECTRONICS_CO_LTD = 117;
    public static final int SARIS_CYCLING_GROUP_INC = 177;
    public static final int SEAT_ES = 293;
    public static final int SEERS_TECHNOLOGY_CO_LTD = 125;
    public static final int SEIKO_EPSON_CORPORATION = 64;
    public static final int SELFLY_BV = 198;
    public static final int SEMILINK_INC = 226;
    public static final int SENNHEISER_COMMUNICATIONS_A_S = 130;
    public static final int SERVER_TECHNOLOGY_INC = 235;
    public static final int SHANGHAI_SUPER_SMART_ELECTRONICS_CO_LTD = 114;
    public static final int SHENZHEN_EXCELSECU_DATA_TECHNOLOGY_COLTD = 193;
    public static final int SIGNIA_TECHNOLOGIES_INC = 27;
    public static final int SILICON_WAVE = 11;
    public static final int SINO_WEALTH_ELECTRONIC_LTD = 289;
    public static final int SIRF_TECHNOLOGY = 80;
    public static final int SKODA_AUTO_AS = 286;
    public static final int SMARTIFIER_OY = 245;
    public static final int SOCKET_MOBILE = 68;
    public static final int SONY_CORPORATION = 301;
    public static final int SONY_ERICSSON_MOBILE_COMMUNICATIONS = 86;
    public static final int SOUND_ID = 111;
    public static final int SPORTIQ = 299;
    public static final int SPORTS_TRACKING_TECHNOLOGIES_LTD = 126;
    public static final int SPOWER_ELECTRONICS_LIMITED = 187;
    public static final int SRMEDIZINELEKTRONIK = 161;
    public static final int STACCATO_COMMUNICATIONS_INC = 77;
    public static final int STALMART_TECHNOLOGY_LIMITED = 191;
    public static final int STARKEY_LABORATORIES_INC = 186;
    public static final int STEELSERIES_APS = 273;
    public static final int STICKNFIND = 249;
    public static final int STOLLMAN_EV_GMBH = 143;
    public static final int STONESTREET_ONE_LLC = 94;
    public static final int ST_MICROELECTRONICS = 48;
    public static final int SUMMIT_DATA_COMMUNICATIONS_INC = 110;
    public static final int SUUNTO_OY = 159;
    public static final int SWIRL_NETWORKS = 181;
    public static final int SYMBOL_TECHNOLOGIES_INC = 42;
    public static final int SYNOPSIS = 49;
    public static final int SYSTEMS_AND_CHIPS_INC = 62;
    public static final int TAIXINGBANG_TECHNOLOGY_HK_CO_LTD = 211;
    public static final int TEMEC_INSTRUMENTS_BV = 300;
    public static final int TENOVIS = 43;
    public static final int TERAX = 56;
    public static final int TEXAS_INSTRUMENTS_INC = 13;
    public static final int THINKOPTICS_INC = 146;
    public static final int THREE_COM = 5;
    public static final int THREE_DIJOY_CORPORATION = 84;
    public static final int THREE_DSP_CORPORATION = 73;
    public static final int TIMEKEEPING_SYSTEMS_INC = 131;
    public static final int TIMEX_GROUP_USA_INC = 214;
    public static final int TOMTOM_INTERNATIONAL_BV = 256;
    public static final int TOPCORN_POSITIONING_SYSTEMS_LLC = 139;
    public static final int TOSHIBA_CORP = 4;
    public static final int TRANSDUCERS_DIRECT_LLC = 268;
    public static final int TRANSILICA_INC = 24;
    public static final int TRELAB_LTD = 183;
    public static final int TTPCOM_LIMITED = 26;
    public static final int TXTR_GMBH = 218;
    public static final int TYPO_PRODUCTS_LLC = 255;
    public static final int TZERO_TECHNOLOGIES_INC = 81;
    public static final int UBIQUITOUS_COMPUTING_TECHNOLOGY_CORPORATION = 261;
    public static final int UNIVERSAL_ELECTRONICS_INC = 147;
    public static final int VALENCETECH_LIMITED = 253;
    public static final int VERTU_CORPORATION_LIMITED = 162;
    public static final int VISTEON_CORPORATION = 167;
    public static final int VIZIO_INC = 88;
    public static final int VOLKSWAGON_AG = 287;
    public static final int VOYETRA_TURTLE_BEACH = 217;
    public static final int VSN_TECHNOLOGIES_INC = 247;
    public static final int VTRACK_SYSTEMS = 233;
    public static final int VYZYBL_INC = 274;
    public static final int WAREHOUSE_INNOVATIONS = 304;
    public static final int WAVEPLUS_TECHNOLOGY_CO_LTD = 35;
    public static final int WICENTRIC_INC = 95;
    public static final int WIDCOMM_INC = 17;
    public static final int WILLIAM_DEMANT_HOLDING_A_S = 263;
    public static final int WIMOTO_TECHNOLOGIES_INC = 279;
    public static final int WITRON_TECHNOLOGY_LIMITED = 241;
    public static final int WIZE_TECHNOLOGY_CO_LTD = 281;
    public static final int WUXI_VIMICRO = 129;
    public static final int XENSR = 276;
    public static final int ZEEVO_INC = 18;
    public static final int ZER01TV_GMBH = 152;
    public static final int ZOMM_LLC = 116;
    public static final int ZSCAN_SOFTWARE = 141;

    public static String getCompanyName(int companyId, String fallback) {
        String name = COMPANY_NAME_MAP.get(companyId);
        return name == null ? fallback : name;
    }

    private static SparseArray<String> populateCompanyNameMap() {
        SparseArray<String> map = new SparseArray<>();
        map.put(0, "Ericsson Technology Licensing");
        map.put(1, "Nokia Mobile Phones");
        map.put(2, "Intel Corp.");
        map.put(3, "IBM Corp.");
        map.put(4, "Toshiba Corp.");
        map.put(5, "3Com");
        map.put(6, "Microsoft");
        map.put(7, "Lucent");
        map.put(8, "Motorola");
        map.put(9, "Infineon Technologies AG");
        map.put(10, "Cambridge Silicon Radio");
        map.put(11, "Silicon Wave");
        map.put(12, "Digianswer A/S");
        map.put(13, "Texas Instruments Inc.");
        map.put(14, "Ceva, Inc. (formerly Parthus Technologies, Inc.)");
        map.put(15, "Broadcom Corporation");
        map.put(16, "Mitel Semiconductor");
        map.put(17, "Widcomm, Inc");
        map.put(18, "Zeevo, Inc.");
        map.put(19, "Atmel Corporation");
        map.put(20, "Mitsubishi Electric Corporation");
        map.put(21, "RTX Telecom A/S");
        map.put(22, "KC Technology Inc.");
        map.put(23, "NewLogic");
        map.put(24, "Transilica, Inc.");
        map.put(25, "Rohde & Schwarz GmbH & Co. KG");
        map.put(26, "TTPCom Limited");
        map.put(27, "Signia Technologies, Inc.");
        map.put(28, "Conexant Systems Inc.");
        map.put(29, "Qualcomm");
        map.put(30, "Inventel");
        map.put(31, "AVM Berlin");
        map.put(32, "BandSpeed, Inc.");
        map.put(33, "Mansella Ltd");
        map.put(34, "NEC Corporation");
        map.put(35, "WavePlus Technology Co., Ltd.");
        map.put(36, "Alcatel");
        map.put(37, "Philips Semiconductors");
        map.put(38, "C Technologies");
        map.put(39, "Open Interface");
        map.put(40, "R F Micro Devices");
        map.put(41, "Hitachi Ltd");
        map.put(42, "Symbol Technologies, Inc.");
        map.put(43, "Tenovis");
        map.put(44, "Macronix International Co. Ltd.");
        map.put(45, "GCT Semiconductor");
        map.put(46, "Norwood Systems");
        map.put(47, "MewTel Technology Inc.");
        map.put(48, "ST Microelectronics");
        map.put(49, "Synopsis");
        map.put(50, "Red-M (Communications) Ltd");
        map.put(51, "Commil Ltd");
        map.put(52, "Computer Access Technology Corporation (CATC)");
        map.put(53, "Eclipse (HQ Espana) S.L.");
        map.put(54, "Renesas Technology Corp.");
        map.put(55, "Mobilian Corporation");
        map.put(56, "Terax");
        map.put(57, "Integrated System Solution Corp.");
        map.put(58, "Matsushita Electric Industrial Co., Ltd.");
        map.put(59, "Gennum Corporation");
        map.put(60, "Research In Motion");
        map.put(61, "IPextreme, Inc.");
        map.put(62, "Systems and Chips, Inc.");
        map.put(63, "Bluetooth SIG, Inc.");
        map.put(64, "Seiko Epson Corporation");
        map.put(65, "Integrated Silicon Solution Taiwan, Inc.");
        map.put(66, "CONWISE Technology Corporation Ltd");
        map.put(67, "PARROT SA");
        map.put(68, "Socket Mobile");
        map.put(69, "Atheros Communications, Inc.");
        map.put(70, "MediaTek, Inc.");
        map.put(71, "Bluegiga");
        map.put(72, "Marvell Technology Group Ltd.");
        map.put(73, "3DSP Corporation");
        map.put(74, "Accel Semiconductor Ltd.");
        map.put(75, "Continental Automotive Systems");
        map.put(76, "Apple, Inc.");
        map.put(77, "Staccato Communications, Inc.");
        map.put(78, "Avago Technologies");
        map.put(79, "APT Licensing Ltd.");
        map.put(80, "SiRF Technology");
        map.put(81, "Tzero Technologies, Inc.");
        map.put(82, "J&M Corporation");
        map.put(83, "Free2move AB");
        map.put(84, "3DiJoy Corporation");
        map.put(85, "Plantronics, Inc.");
        map.put(86, "Sony Ericsson Mobile Communications");
        map.put(87, "Harman International Industries, Inc.");
        map.put(88, "Vizio, Inc.");
        map.put(89, "Nordic Semiconductor ASA");
        map.put(90, "EM Microelectronic-Marin SA");
        map.put(91, "Ralink Technology Corporation");
        map.put(92, "Belkin International, Inc.");
        map.put(93, "Realtek Semiconductor Corporation");
        map.put(94, "Stonestreet One, LLC");
        map.put(95, "Wicentric, Inc.");
        map.put(96, "RivieraWaves S.A.S");
        map.put(97, "RDA Microelectronics");
        map.put(98, "Gibson Guitars");
        map.put(99, "MiCommand Inc.");
        map.put(100, "Band XI International, LLC");
        map.put(101, "Hewlett-Packard Company");
        map.put(102, "9Solutions Oy");
        map.put(103, "GN Netcom A/S");
        map.put(104, "General Motors");
        map.put(105, "A&D Engineering, Inc.");
        map.put(106, "MindTree Ltd.");
        map.put(107, "Polar Electro OY");
        map.put(108, "Beautiful Enterprise Co., Ltd.");
        map.put(109, "BriarTek, Inc.");
        map.put(110, "Summit Data Communications, Inc.");
        map.put(111, "Sound ID");
        map.put(112, "Monster, LLC");
        map.put(113, "connectBlue AB");
        map.put(114, "ShangHai Super Smart Electronics Co. Ltd.");
        map.put(115, "Group Sense Ltd.");
        map.put(116, "Zomm, LLC");
        map.put(117, "Samsung Electronics Co. Ltd.");
        map.put(118, "Creative Technology Ltd.");
        map.put(119, "Laird Technologies");
        map.put(120, "Nike, Inc.");
        map.put(121, "lesswire AG");
        map.put(122, "MStar Semiconductor, Inc.");
        map.put(123, "Hanlynn Technologies");
        map.put(124, "A & R Cambridge");
        map.put(125, "Seers Technology Co. Ltd");
        map.put(126, "Sports Tracking Technologies Ltd.");
        map.put(127, "Autonet Mobile");
        map.put(128, "DeLorme Publishing Company, Inc.");
        map.put(129, "WuXi Vimicro");
        map.put(130, "Sennheiser Communications A/S");
        map.put(131, "TimeKeeping Systems, Inc.");
        map.put(132, "Ludus Helsinki Ltd.");
        map.put(133, "BlueRadios, Inc.");
        map.put(134, "equinox AG");
        map.put(135, "Garmin International, Inc.");
        map.put(136, "Ecotest");
        map.put(137, "GN ReSound A/S");
        map.put(138, "Jawbone");
        map.put(139, "Topcorn Positioning Systems, LLC");
        map.put(QUALCOMM_RETAIL_SOLUTIONS_INC_FORMERLY_QUALCOMM_LABS_INC, "Qualcomm Retail Solutions, Inc. (formerly Qualcomm Labs, Inc.)");
        map.put(ZSCAN_SOFTWARE, "Zscan Software");
        map.put(QUINTIC_CORP, "Quintic Corp.");
        map.put(STOLLMAN_EV_GMBH, "Stollman E+V GmbH");
        map.put(144, "Funai Electric Co., Ltd.");
        map.put(145, "Advanced PANMOBIL Systems GmbH & Co. KG");
        map.put(146, "ThinkOptics, Inc.");
        map.put(147, "Universal Electronics, Inc.");
        map.put(148, "Airoha Technology Corp.");
        map.put(149, "NEC Lighting, Ltd.");
        map.put(150, "ODM Technology, Inc.");
        map.put(151, "ConnecteDevice Ltd.");
        map.put(152, "zer01.tv GmbH");
        map.put(153, "i.Tech Dynamic Global Distribution Ltd.");
        map.put(ALPWISE, "Alpwise");
        map.put(JIANGSU_TOPPOWER_AUTOMOTIVE_ELECTRONICS_CO_LTD, "Jiangsu Toppower Automotive Electronics Co., Ltd.");
        map.put(COLORFY_INC, "Colorfy, Inc.");
        map.put(GEOFORCE_INC, "Geoforce Inc.");
        map.put(BOSE_CORPORATION, "Bose Corporation");
        map.put(SUUNTO_OY, "Suunto Oy");
        map.put(160, "Kensington Computer Products Group");
        map.put(SRMEDIZINELEKTRONIK, "SR-Medizinelektronik");
        map.put(VERTU_CORPORATION_LIMITED, "Vertu Corporation Limited");
        map.put(META_WATCH_LTD, "Meta Watch Ltd.");
        map.put(LINAK_A_S, "LINAK A/S");
        map.put(OTL_DYNAMICS_LLC, "OTL Dynamics LLC");
        map.put(PANDA_OCEAN_INC, "Panda Ocean Inc.");
        map.put(VISTEON_CORPORATION, "Visteon Corporation");
        map.put(ARP_DEVICES_LIMITED, "ARP Devices Limited");
        map.put(MAGNETI_MARELLI_SPA, "Magneti Marelli S.p.A");
        map.put(CAEN_RFID_SRL, "CAEN RFID srl");
        map.put(INGENIEURSYSTEMGRUPPE_ZAHN_GMBH, "Ingenieur-Systemgruppe Zahn GmbH");
        map.put(GREEN_THROTTLE_GAMES, "Green Throttle Games");
        map.put(PETER_SYSTEMTECHNIK_GMBH, "Peter Systemtechnik GmbH");
        map.put(OMEGAWAVE_OY, "Omegawave Oy");
        map.put(CINETIX, "Cinetix");
        map.put(PASSIF_SEMICONDUCTOR_CORP, "Passif Semiconductor Corp");
        map.put(SARIS_CYCLING_GROUP_INC, "Saris Cycling Group, Inc");
        map.put(BEKEY_A_S, "Bekey A/S");
        map.put(CLARINOX_TECHNOLOGIES_PTY_LTD, "Clarinox Technologies Pty. Ltd.");
        map.put(180, "BDE Technology Co., Ltd.");
        map.put(SWIRL_NETWORKS, "Swirl Networks");
        map.put(MESO_INTERNATIONAL, "Meso international");
        map.put(TRELAB_LTD, "TreLab Ltd");
        map.put(QUALCOMM_INNOVATION_CENTER_INC_QUIC, "Qualcomm Innovation Center, Inc. (QuIC)");
        map.put(JOHNSON_CONTROLS_INC, "Johnson Controls, Inc.");
        map.put(STARKEY_LABORATORIES_INC, "Starkey Laboratories Inc.");
        map.put(SPOWER_ELECTRONICS_LIMITED, "S-Power Electronics Limited");
        map.put(ACE_SENSOR_INC, "Ace Sensor Inc");
        map.put(189, "Aplix Corporation");
        map.put(190, "AAMP of America");
        map.put(STALMART_TECHNOLOGY_LIMITED, "Stalmart Technology Limited");
        map.put(192, "AMICCOM Electronics Corporation");
        map.put(193, "Shenzhen Excelsecu Data Technology Co.,Ltd");
        map.put(194, "Geneq Inc.");
        map.put(195, "adidas AG");
        map.put(196, "LG Electronics");
        map.put(197, "Onset Computer Corporation");
        map.put(SELFLY_BV, "Selfly BV");
        map.put(QUUPPA_OY, "Quuppa Oy.");
        map.put(200, "GeLo Inc");
        map.put(EVLUMA, "Evluma");
        map.put(MC10, "MC10");
        map.put(BINAURIC_SE, "Binauric SE");
        map.put(BEATS_ELECTRONICS, "Beats Electronics");
        map.put(MICROCHIP_TECHNOLOGY_INC, "Microchip Technology Inc.");
        map.put(ELGATO_SYSTEMS_GMBH, "Elgato Systems GmbH");
        map.put(ARCHOS_SA, "ARCHOS SA");
        map.put(DEXCOM_INC, "Dexcom, Inc.");
        map.put(POLAR_ELECTRO_EUROPE_BV, "Polar Electro Europe B.V.");
        map.put(DIALOG_SEMICONDUCTOR_BV, "Dialog Semiconductor B.V.");
        map.put(TAIXINGBANG_TECHNOLOGY_HK_CO_LTD, "Taixingbang Technology (HK) Co,. LTD.");
        map.put(KAWANTECH, "Kawantech");
        map.put(AUSTCO_COMMUNICATION_SYSTEMS, "Austco Communication Systems");
        map.put(TIMEX_GROUP_USA_INC, "Timex Group USA, Inc.");
        map.put(QUALCOMM_TECHNOLOGIES_INC, "Qualcomm Technologies, Inc.");
        map.put(QUALCOMM_CONNECTED_EXPERIENCES_INC, "Qualcomm Connected Experiences, Inc.");
        map.put(VOYETRA_TURTLE_BEACH, "Voyetra Turtle Beach");
        map.put(TXTR_GMBH, "txtr GmbH");
        map.put(BIOSENTRONICS, "Biosentronics");
        map.put(PROCTER_GAMBLE, "Procter & Gamble");
        map.put(HOSIDEN_CORPORATION, "Hosiden Corporation");
        map.put(MUZIK_LLC, "Muzik LLC");
        map.put(MISFIT_WEARABLES_CORP, "Misfit Wearables Corp");
        map.put(224, "Google");
        map.put(DANLERS_LTD, "Danlers Ltd");
        map.put(SEMILINK_INC, "Semilink Inc");
        map.put(INMUSIC_BRANDS_INC, "inMusic Brands, Inc");
        map.put(LS_RESEARCH_INC, "L.S. Research Inc.");
        map.put(EDEN_SOFTWARE_CONSULTANTS_LTD, "Eden Software Consultants Ltd.");
        map.put(FRESHTEMP, "Freshtemp");
        map.put(KS_TECHNOLOGIES, "KS Technologies");
        map.put(ACTS_TECHNOLOGIES, "ACTS Technologies");
        map.put(233, "Vtrack Systems");
        map.put(NIELSENKELLERMAN_COMPANY, "Nielsen-Kellerman Company");
        map.put(SERVER_TECHNOLOGY_INC, "Server Technology, Inc.");
        map.put(BIORESEARCH_ASSOCIATES, "BioResearch Associates");
        map.put(JOLLY_LOGIC_LLC, "Jolly Logic, LLC");
        map.put(ABOVE_AVERAGE_OUTCOMES_INC, "Above Average Outcomes, Inc.");
        map.put(BITSPLITTERS_GMBH, "Bitsplitters GmbH");
        map.put(240, "PayPal, Inc.");
        map.put(WITRON_TECHNOLOGY_LIMITED, "Witron Technology Limited");
        map.put(MORSE_PROJECT_INC, "Morse Project Inc.");
        map.put(KENT_DISPLAYS_INC, "Kent Displays Inc.");
        map.put(244, "Nautilus Inc.");
        map.put(245, "Smartifier Oy");
        map.put(ELCOMETER_LIMITED, "Elcometer Limited");
        map.put(VSN_TECHNOLOGIES_INC, "VSN Technologies Inc.");
        map.put(ACEUNI_CORP_LTD, "AceUni Corp., Ltd.");
        map.put(STICKNFIND, "StickNFind");
        map.put(250, "Crystal Code AB");
        map.put(KOUKAAM_AS, "KOUKAAM a.s.");
        map.put(DELPHI_CORPORATION, "Delphi Corporation");
        map.put(VALENCETECH_LIMITED, "ValenceTech Limited");
        map.put(RESERVED, "Reserved");
        map.put(255, "Typo Products, LLC");
        map.put(256, "TomTom International BV");
        map.put(257, "Fugoo, Inc");
        map.put(KEISER_CORPORATION, "Keiser Corporation");
        map.put(BANG_OLUFSEN_A_S, "Bang & Olufsen A/S");
        map.put(PLUS_LOCATIONS_SYSTEMS_PTY_LTD, "PLUS Locations Systems Pty Ltd");
        map.put(UBIQUITOUS_COMPUTING_TECHNOLOGY_CORPORATION, "Ubiquitous Computing Technology Corporation");
        map.put(INNOVATIVE_YACHTTER_SOLUTIONS, "Innovative Yachtter Solutions");
        map.put(WILLIAM_DEMANT_HOLDING_A_S, "William Demant Holding A/S");
        map.put(CHICONY_ELECTRONICS_CO_LTD, "Chicony Electronics Co., Ltd.");
        map.put(ATUS_BV, "Atus BV");
        map.put(CODEGATE_LTD, "Codegate Ltd.");
        map.put(ERI_INC, "ERi, Inc.");
        map.put(TRANSDUCERS_DIRECT_LLC, "Transducers Direct, LLC");
        map.put(FUJITSU_TEN_LIMITED, "Fujitsu Ten Limited");
        map.put(270, "Audi AG");
        map.put(HISILICON_TECHNOLOGIES_CO_LTD, "HiSilicon Technologies Co., Ltd.");
        map.put(NIPPON_SEIKI_CO_LTD, "Nippon Seiki Co., Ltd.");
        map.put(STEELSERIES_APS, "Steelseries ApS");
        map.put(VYZYBL_INC, "vyzybl Inc.");
        map.put(OPENBRAIN_TECHNOLOGIES_CO_LTD, "Openbrain Technologies, Co., Ltd.");
        map.put(XENSR, "Xensr");
        map.put(ESOLUTIONS, "e.solutions");
        map.put(ONE_OAK_TECHNOLOGIES, "1OAK Technologies");
        map.put(WIMOTO_TECHNOLOGIES_INC, "Wimoto Technologies Inc");
        map.put(RADIUS_NETWORKS_INC, "Radius Networks, Inc.");
        map.put(WIZE_TECHNOLOGY_CO_LTD, "Wize Technology Co., Ltd.");
        map.put(QUALCOMM_LABS_INC, "Qualcomm Labs, Inc.");
        map.put(ARUBA_NETWORKS, "Aruba Networks");
        map.put(BAIDU, "Baidu");
        map.put(ARENDI_AG, "Arendi AG");
        map.put(SKODA_AUTO_AS, "Skoda Auto a.s.");
        map.put(VOLKSWAGON_AG, "Volkswagon AG");
        map.put(PORSCHE_AG, "Porsche AG");
        map.put(SINO_WEALTH_ELECTRONIC_LTD, "Sino Wealth Electronic Ltd.");
        map.put(AIRTURN_INC, "AirTurn, Inc.");
        map.put(291, "Kinsa, Inc.");
        map.put(HID_GLOBAL, "HID Global");
        map.put(SEAT_ES, "SEAT es");
        map.put(PROMETHEAN_LTD, "Promethean Ltd.");
        map.put(SALUTICA_ALLIED_SOLUTIONS, "Salutica Allied Solutions");
        map.put(GPSI_GROUP_PTY_LTD, "GPSI Group Pty Ltd");
        map.put(NIMBLE_DEVICES_OY, "Nimble Devices Oy");
        map.put(CHANGZHOU_YONGSE_INFOTECH_CO_LTD, "Changzhou Yongse Infotech Co., Ltd");
        map.put(SPORTIQ, "SportIQ");
        map.put(300, "TEMEC Instruments B.V.");
        map.put(SONY_CORPORATION, "Sony Corporation");
        map.put(ASSA_ABLOY, "ASSA ABLOY");
        map.put(CLARION_CO_LTD, "Clarion Co., Ltd.");
        map.put(WAREHOUSE_INNOVATIONS, "Warehouse Innovations");
        map.put(CYPRESS_SEMICONDUCTOR_CORPORATION, "Cypress Semiconductor Corporation");
        map.put(MADS_INC, "MADS Inc");
        map.put(307, "Blue Maestro Limited");
        map.put(308, "Resolution Products, Inc.");
        map.put(AIREWEAR_LLC, "Airewear LLC");
        map.put(ETC_SP_ZOO, "ETC sp. z.o.o.");
        map.put(PRESTIGIO_PLAZA_LTD, "Prestigio Plaza Ltd.");
        return map;
    }
}
