package com.freevisiontech.fvmobile.fragment;

import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.TextView;
import butterknife.ButterKnife;
import butterknife.internal.DebouncingOnClickListener;
import com.alanapi.switchbutton.SwitchButton;
import com.freevisiontech.fvmobile.C0853R;
import com.freevisiontech.fvmobile.fragment.FVAdvancedSetPTZFragment;

public class FVAdvancedSetPTZFragment$$ViewBinder<T extends FVAdvancedSetPTZFragment> implements ButterKnife.ViewBinder<T> {
    public void bind(ButterKnife.Finder finder, final T target, Object source) {
        target.seekbar_pitch_deadzone = (SeekBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.seekbar_pitch_deadzone, "field 'seekbar_pitch_deadzone'"), C0853R.C0855id.seekbar_pitch_deadzone, "field 'seekbar_pitch_deadzone'");
        target.seekbar_yaw_deadzone = (SeekBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.seekbar_yaw_deadzone, "field 'seekbar_yaw_deadzone'"), C0853R.C0855id.seekbar_yaw_deadzone, "field 'seekbar_yaw_deadzone'");
        target.seekbar_roll_deadzone = (SeekBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.seekbar_roll_deadzone, "field 'seekbar_roll_deadzone'"), C0853R.C0855id.seekbar_roll_deadzone, "field 'seekbar_roll_deadzone'");
        target.phone_check = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.phone_check, "field 'phone_check'"), C0853R.C0855id.phone_check, "field 'phone_check'");
        target.calibration = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.calibration, "field 'calibration'"), C0853R.C0855id.calibration, "field 'calibration'");
        target.tv_pitch_pg_deadzone = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_pitch_pg_deadzone, "field 'tv_pitch_pg_deadzone'"), C0853R.C0855id.tv_pitch_pg_deadzone, "field 'tv_pitch_pg_deadzone'");
        target.tv_yaw_pg_deadzone = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_yaw_pg_deadzone, "field 'tv_yaw_pg_deadzone'"), C0853R.C0855id.tv_yaw_pg_deadzone, "field 'tv_yaw_pg_deadzone'");
        target.tv_roll_pg_deadzone = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_roll_pg_deadzone, "field 'tv_roll_pg_deadzone'"), C0853R.C0855id.tv_roll_pg_deadzone, "field 'tv_roll_pg_deadzone'");
        target.seekbar_pitch_speed = (SeekBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.seekbar_pitch_speed, "field 'seekbar_pitch_speed'"), C0853R.C0855id.seekbar_pitch_speed, "field 'seekbar_pitch_speed'");
        target.seekbar_yaw_speed = (SeekBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.seekbar_yaw_speed, "field 'seekbar_yaw_speed'"), C0853R.C0855id.seekbar_yaw_speed, "field 'seekbar_yaw_speed'");
        target.seekbar_roll_spped = (SeekBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.seekbar_roll_spped, "field 'seekbar_roll_spped'"), C0853R.C0855id.seekbar_roll_spped, "field 'seekbar_roll_spped'");
        target.tv_pitch_pg_speed = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_pitch_pg_speed, "field 'tv_pitch_pg_speed'"), C0853R.C0855id.tv_pitch_pg_speed, "field 'tv_pitch_pg_speed'");
        target.tv_yaw_pg_speed = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_yaw_pg_speed, "field 'tv_yaw_pg_speed'"), C0853R.C0855id.tv_yaw_pg_speed, "field 'tv_yaw_pg_speed'");
        target.tv_roll_pg_speed = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_roll_pg_speed, "field 'tv_roll_pg_speed'"), C0853R.C0855id.tv_roll_pg_speed, "field 'tv_roll_pg_speed'");
        target.ll_no_connect_ptz = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_no_connect_ptz, "field 'll_no_connect_ptz'"), C0853R.C0855id.ll_no_connect_ptz, "field 'll_no_connect_ptz'");
        target.scrollview = (ScrollView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.scrollview, "field 'scrollview'"), C0853R.C0855id.scrollview, "field 'scrollview'");
        target.ll_connect_ptz = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_connect_ptz, "field 'll_connect_ptz'"), C0853R.C0855id.ll_connect_ptz, "field 'll_connect_ptz'");
        target.rl_walk_model = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_walk_model, "field 'rl_walk_model'"), C0853R.C0855id.rl_walk_model, "field 'rl_walk_model'");
        target.iv_walk_select = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_walk_select, "field 'iv_walk_select'"), C0853R.C0855id.iv_walk_select, "field 'iv_walk_select'");
        target.rl_sport_model = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_sport_model, "field 'rl_sport_model'"), C0853R.C0855id.rl_sport_model, "field 'rl_sport_model'");
        target.iv_sport_select = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_sport_select, "field 'iv_sport_select'"), C0853R.C0855id.iv_sport_select, "field 'iv_sport_select'");
        target.rl_custom_model = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_custom_model, "field 'rl_custom_model'"), C0853R.C0855id.rl_custom_model, "field 'rl_custom_model'");
        target.iv_custom_select = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_custom_select, "field 'iv_custom_select'"), C0853R.C0855id.iv_custom_select, "field 'iv_custom_select'");
        target.rl_roll_model = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_roll_model, "field 'rl_roll_model'"), C0853R.C0855id.rl_roll_model, "field 'rl_roll_model'");
        target.iv_roll_select = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_roll_select, "field 'iv_roll_select'"), C0853R.C0855id.iv_roll_select, "field 'iv_roll_select'");
        target.rl_exposure_model = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_exposure_model, "field 'rl_exposure_model'"), C0853R.C0855id.rl_exposure_model, "field 'rl_exposure_model'");
        target.iv_exposure_select = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_exposure_select, "field 'iv_exposure_select'"), C0853R.C0855id.iv_exposure_select, "field 'iv_exposure_select'");
        target.rl_custom_isvisible = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_custom_isvisible, "field 'rl_custom_isvisible'"), C0853R.C0855id.rl_custom_isvisible, "field 'rl_custom_isvisible'");
        target.reset_to_default = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.reset_to_default, "field 'reset_to_default'"), C0853R.C0855id.reset_to_default, "field 'reset_to_default'");
        target.switchButton = (SwitchButton) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.switchButton, "field 'switchButton'"), C0853R.C0855id.switchButton, "field 'switchButton'");
        target.layout_advance_dead_zone_what = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.layout_advance_dead_zone_what, "field 'layout_advance_dead_zone_what'"), C0853R.C0855id.layout_advance_dead_zone_what, "field 'layout_advance_dead_zone_what'");
        target.layout_advance_follow_speed_what = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.layout_advance_follow_speed_what, "field 'layout_advance_follow_speed_what'"), C0853R.C0855id.layout_advance_follow_speed_what, "field 'layout_advance_follow_speed_what'");
        target.long_click_mode_and_roll_mode_tv = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.long_click_mode_and_roll_mode_tv, "field 'long_click_mode_and_roll_mode_tv'"), C0853R.C0855id.long_click_mode_and_roll_mode_tv, "field 'long_click_mode_and_roll_mode_tv'");
        target.seekbar_roll_axle = (SeekBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.seekbar_roll_axle, "field 'seekbar_roll_axle'"), C0853R.C0855id.seekbar_roll_axle, "field 'seekbar_roll_axle'");
        target.roll_axle_num_tv = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.roll_axle_num_tv, "field 'roll_axle_num_tv'"), C0853R.C0855id.roll_axle_num_tv, "field 'roll_axle_num_tv'");
        target.long_press_mode_focus_rl = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.long_press_mode_focus_rl, "field 'long_press_mode_focus_rl'"), C0853R.C0855id.long_press_mode_focus_rl, "field 'long_press_mode_focus_rl'");
        target.long_press_mode_focus_switch = (SwitchButton) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.long_press_mode_focus_switch, "field 'long_press_mode_focus_switch'"), C0853R.C0855id.long_press_mode_focus_switch, "field 'long_press_mode_focus_switch'");
        target.long_press_mode_focus_divider = (View) finder.findRequiredView(source, C0853R.C0855id.long_press_mode_focus_divider, "field 'long_press_mode_focus_divider'");
        target.custom_for_speed2_divider = (View) finder.findRequiredView(source, C0853R.C0855id.custom_for_speed2_divider, "field 'custom_for_speed2_divider'");
        target.wireless_charging_rl = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.wireless_charging_rl, "field 'wireless_charging_rl'"), C0853R.C0855id.wireless_charging_rl, "field 'wireless_charging_rl'");
        target.switchButton_charging = (com.kyleduo.switchbutton.SwitchButton) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.switchButton_charging, "field 'switchButton_charging'"), C0853R.C0855id.switchButton_charging, "field 'switchButton_charging'");
        target.wireless_charging_tip = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.wireless_charging_tip, "field 'wireless_charging_tip'"), C0853R.C0855id.wireless_charging_tip, "field 'wireless_charging_tip'");
        View view = (View) finder.findRequiredView(source, C0853R.C0855id.control_default_camera, "field 'control_default_camera' and method 'onViewClicked'");
        target.control_default_camera = (RelativeLayout) finder.castView(view, C0853R.C0855id.control_default_camera, "field 'control_default_camera'");
        view.setOnClickListener(new DebouncingOnClickListener() {
            public void doClick(View p0) {
                target.onViewClicked();
            }
        });
        target.controlDefaultCameraDesc = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.control_default_camera_desc, "field 'controlDefaultCameraDesc'"), C0853R.C0855id.control_default_camera_desc, "field 'controlDefaultCameraDesc'");
        target.fn_title_tv = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.fn_title_tv, "field 'fn_title_tv'"), C0853R.C0855id.fn_title_tv, "field 'fn_title_tv'");
        target.fv_setting_rl = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.fv_setting_rl, "field 'fv_setting_rl'"), C0853R.C0855id.fv_setting_rl, "field 'fv_setting_rl'");
        target.iv_fn_follow_hand = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_fn_follow_hand, "field 'iv_fn_follow_hand'"), C0853R.C0855id.iv_fn_follow_hand, "field 'iv_fn_follow_hand'");
        target.rl_fn_follow_hand = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_fn_follow_hand, "field 'rl_fn_follow_hand'"), C0853R.C0855id.rl_fn_follow_hand, "field 'rl_fn_follow_hand'");
        target.iv_fn_flash = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_fn_flash, "field 'iv_fn_flash'"), C0853R.C0855id.iv_fn_flash, "field 'iv_fn_flash'");
        target.rl_fn_flash = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_fn_flash, "field 'rl_fn_flash'"), C0853R.C0855id.rl_fn_flash, "field 'rl_fn_flash'");
        target.iv_fn_white_balance = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_fn_white_balance, "field 'iv_fn_white_balance'"), C0853R.C0855id.iv_fn_white_balance, "field 'iv_fn_white_balance'");
        target.rl_fn_white_balance = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_fn_white_balance, "field 'rl_fn_white_balance'"), C0853R.C0855id.rl_fn_white_balance, "field 'rl_fn_white_balance'");
        target.iv_fn_wireless_charging = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_fn_wireless_charging, "field 'iv_fn_wireless_charging'"), C0853R.C0855id.iv_fn_wireless_charging, "field 'iv_fn_wireless_charging'");
        target.rl_fn_wireless_charging = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_fn_wireless_charging, "field 'rl_fn_wireless_charging'"), C0853R.C0855id.rl_fn_wireless_charging, "field 'rl_fn_wireless_charging'");
        target.iv_fn_lock_mode = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_fn_lock_mode, "field 'iv_fn_lock_mode'"), C0853R.C0855id.iv_fn_lock_mode, "field 'iv_fn_lock_mode'");
        target.rl_fn_lock_mode = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_fn_lock_mode, "field 'rl_fn_lock_mode'"), C0853R.C0855id.rl_fn_lock_mode, "field 'rl_fn_lock_mode'");
        target.roll_axle_rl = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.roll_axle_rl, "field 'roll_axle_rl'"), C0853R.C0855id.roll_axle_rl, "field 'roll_axle_rl'");
        target.rl_pitch_spped = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_pitch_spped, "field 'rl_pitch_spped'"), C0853R.C0855id.rl_pitch_spped, "field 'rl_pitch_spped'");
        target.rl_yaw_speed = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_yaw_speed, "field 'rl_yaw_speed'"), C0853R.C0855id.rl_yaw_speed, "field 'rl_yaw_speed'");
        target.rl_roll_speed = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_roll_speed, "field 'rl_roll_speed'"), C0853R.C0855id.rl_roll_speed, "field 'rl_roll_speed'");
        target.rl_pitch_axis = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_pitch_axis, "field 'rl_pitch_axis'"), C0853R.C0855id.rl_pitch_axis, "field 'rl_pitch_axis'");
        target.rl_yall_axis = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_yall_axis, "field 'rl_yall_axis'"), C0853R.C0855id.rl_yall_axis, "field 'rl_yall_axis'");
        target.rl_roll_axis = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_roll_axis, "field 'rl_roll_axis'"), C0853R.C0855id.rl_roll_axis, "field 'rl_roll_axis'");
    }

    public void unbind(T target) {
        target.seekbar_pitch_deadzone = null;
        target.seekbar_yaw_deadzone = null;
        target.seekbar_roll_deadzone = null;
        target.phone_check = null;
        target.calibration = null;
        target.tv_pitch_pg_deadzone = null;
        target.tv_yaw_pg_deadzone = null;
        target.tv_roll_pg_deadzone = null;
        target.seekbar_pitch_speed = null;
        target.seekbar_yaw_speed = null;
        target.seekbar_roll_spped = null;
        target.tv_pitch_pg_speed = null;
        target.tv_yaw_pg_speed = null;
        target.tv_roll_pg_speed = null;
        target.ll_no_connect_ptz = null;
        target.scrollview = null;
        target.ll_connect_ptz = null;
        target.rl_walk_model = null;
        target.iv_walk_select = null;
        target.rl_sport_model = null;
        target.iv_sport_select = null;
        target.rl_custom_model = null;
        target.iv_custom_select = null;
        target.rl_roll_model = null;
        target.iv_roll_select = null;
        target.rl_exposure_model = null;
        target.iv_exposure_select = null;
        target.rl_custom_isvisible = null;
        target.reset_to_default = null;
        target.switchButton = null;
        target.layout_advance_dead_zone_what = null;
        target.layout_advance_follow_speed_what = null;
        target.long_click_mode_and_roll_mode_tv = null;
        target.seekbar_roll_axle = null;
        target.roll_axle_num_tv = null;
        target.long_press_mode_focus_rl = null;
        target.long_press_mode_focus_switch = null;
        target.long_press_mode_focus_divider = null;
        target.custom_for_speed2_divider = null;
        target.wireless_charging_rl = null;
        target.switchButton_charging = null;
        target.wireless_charging_tip = null;
        target.control_default_camera = null;
        target.controlDefaultCameraDesc = null;
        target.fn_title_tv = null;
        target.fv_setting_rl = null;
        target.iv_fn_follow_hand = null;
        target.rl_fn_follow_hand = null;
        target.iv_fn_flash = null;
        target.rl_fn_flash = null;
        target.iv_fn_white_balance = null;
        target.rl_fn_white_balance = null;
        target.iv_fn_wireless_charging = null;
        target.rl_fn_wireless_charging = null;
        target.iv_fn_lock_mode = null;
        target.rl_fn_lock_mode = null;
        target.roll_axle_rl = null;
        target.rl_pitch_spped = null;
        target.rl_yaw_speed = null;
        target.rl_roll_speed = null;
        target.rl_pitch_axis = null;
        target.rl_yall_axis = null;
        target.rl_roll_axis = null;
    }
}
