package com.freevisiontech.fvmobile.fragment;

import android.support.p003v7.widget.RecyclerView;
import android.view.View;
import android.widget.Chronometer;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.RelativeLayout;
import android.widget.SeekBar;
import android.widget.TextView;
import butterknife.ButterKnife;
import com.freevisiontech.fvmobile.C0853R;
import com.freevisiontech.fvmobile.fragment.FVContentFragment;

public class FVContentFragment$$ViewBinder<T extends FVContentFragment> implements ButterKnife.ViewBinder<T> {
    public void bind(ButterKnife.Finder finder, T target, Object source) {
        target.iconGriding = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon_griding, "field 'iconGriding'"), C0853R.C0855id.icon_griding, "field 'iconGriding'");
        target.llSeekbar = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_seekbar, "field 'llSeekbar'"), C0853R.C0855id.ll_seekbar, "field 'llSeekbar'");
        target.llSeekbarInside = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_seekbar_inside, "field 'llSeekbarInside'"), C0853R.C0855id.ll_seekbar_inside, "field 'llSeekbarInside'");
        target.tvTimer = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_timer, "field 'tvTimer'"), C0853R.C0855id.tv_timer, "field 'tvTimer'");
        target.btnManualFocus = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.btn_manual_focus, "field 'btnManualFocus'"), C0853R.C0855id.btn_manual_focus, "field 'btnManualFocus'");
        target.rlFocus = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_focus, "field 'rlFocus'"), C0853R.C0855id.rl_focus, "field 'rlFocus'");
        target.contentLayout = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.content_layout, "field 'contentLayout'"), C0853R.C0855id.content_layout, "field 'contentLayout'");
        target.content_layout_scale = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.content_layout_scale, "field 'content_layout_scale'"), C0853R.C0855id.content_layout_scale, "field 'content_layout_scale'");
        target.content_layout_parameter_display = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.content_layout_parameter_display, "field 'content_layout_parameter_display'"), C0853R.C0855id.content_layout_parameter_display, "field 'content_layout_parameter_display'");
        target.timer = (Chronometer) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.timer, "field 'timer'"), C0853R.C0855id.timer, "field 'timer'");
        target.timer_size_all = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.timer_size_all, "field 'timer_size_all'"), C0853R.C0855id.timer_size_all, "field 'timer_size_all'");
        target.timer_size_all_view = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.timer_size_all_view, "field 'timer_size_all_view'"), C0853R.C0855id.timer_size_all_view, "field 'timer_size_all_view'");
        target.timer_horizontal = (Chronometer) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.timer_horizontal, "field 'timer_horizontal'"), C0853R.C0855id.timer_horizontal, "field 'timer_horizontal'");
        target.timer_size_all_horizontal = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.timer_size_all_horizontal, "field 'timer_size_all_horizontal'"), C0853R.C0855id.timer_size_all_horizontal, "field 'timer_size_all_horizontal'");
        target.timer_size_all_view_horizontal = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.timer_size_all_view_horizontal, "field 'timer_size_all_view_horizontal'"), C0853R.C0855id.timer_size_all_view_horizontal, "field 'timer_size_all_view_horizontal'");
        target.timer_video_record_start_linear_horizontal = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.timer_video_record_start_linear_horizontal, "field 'timer_video_record_start_linear_horizontal'"), C0853R.C0855id.timer_video_record_start_linear_horizontal, "field 'timer_video_record_start_linear_horizontal'");
        target.timer_video_record_start_linear = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.timer_video_record_start_linear, "field 'timer_video_record_start_linear'"), C0853R.C0855id.timer_video_record_start_linear, "field 'timer_video_record_start_linear'");
        target.llFullShot = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_full_shot, "field 'llFullShot'"), C0853R.C0855id.ll_full_shot, "field 'llFullShot'");
        target.iconFullShot = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon_full_shot, "field 'iconFullShot'"), C0853R.C0855id.icon_full_shot, "field 'iconFullShot'");
        target.btnFullShotCancel = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.btn_full_shot_cancel, "field 'btnFullShotCancel'"), C0853R.C0855id.btn_full_shot_cancel, "field 'btnFullShotCancel'");
        target.rlPhotoSynthesis = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_photo_synthesis, "field 'rlPhotoSynthesis'"), C0853R.C0855id.rl_photo_synthesis, "field 'rlPhotoSynthesis'");
        target.pbSynthesis = (ProgressBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.pb_synthesis, "field 'pbSynthesis'"), C0853R.C0855id.pb_synthesis, "field 'pbSynthesis'");
        target.fragment_content_two_ll = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.fragment_content_two_ll, "field 'fragment_content_two_ll'"), C0853R.C0855id.fragment_content_two_ll, "field 'fragment_content_two_ll'");
        target.rlBright = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_bright, "field 'rlBright'"), C0853R.C0855id.rl_bright, "field 'rlBright'");
        target.rlBright2 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_bright2, "field 'rlBright2'"), C0853R.C0855id.rl_bright2, "field 'rlBright2'");
        target.seekbarBrightness2 = (SeekBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.seekbar_brightness2, "field 'seekbarBrightness2'"), C0853R.C0855id.seekbar_brightness2, "field 'seekbarBrightness2'");
        target.seekbar_brightness2_view = (View) finder.findRequiredView(source, C0853R.C0855id.seekbar_brightness2_view, "field 'seekbar_brightness2_view'");
        target.seekbar_brightness_view = (View) finder.findRequiredView(source, C0853R.C0855id.seekbar_brightness_view, "field 'seekbar_brightness_view'");
        target.linear_timer = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.linear_timer, "field 'linear_timer'"), C0853R.C0855id.linear_timer, "field 'linear_timer'");
        target.chro_timer = (Chronometer) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.chro_timer, "field 'chro_timer'"), C0853R.C0855id.chro_timer, "field 'chro_timer'");
        target.chro_all_timer = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.chro_all_timer, "field 'chro_all_timer'"), C0853R.C0855id.chro_all_timer, "field 'chro_all_timer'");
        target.linear_timer_progress_bar = (ProgressBar) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.linear_timer_progress_bar, "field 'linear_timer_progress_bar'"), C0853R.C0855id.linear_timer_progress_bar, "field 'linear_timer_progress_bar'");
        target.linear_timer_progress_recycler = (RecyclerView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.linear_timer_progress_recycler, "field 'linear_timer_progress_recycler'"), C0853R.C0855id.linear_timer_progress_recycler, "field 'linear_timer_progress_recycler'");
        target.tv_chro_all_timer_center = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_chro_all_timer_center, "field 'tv_chro_all_timer_center'"), C0853R.C0855id.tv_chro_all_timer_center, "field 'tv_chro_all_timer_center'");
        target.rl_timer_progress_bar = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_timer_progress_bar, "field 'rl_timer_progress_bar'"), C0853R.C0855id.rl_timer_progress_bar, "field 'rl_timer_progress_bar'");
        target.rl_focus_relative = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.rl_focus_relative, "field 'rl_focus_relative'"), C0853R.C0855id.rl_focus_relative, "field 'rl_focus_relative'");
        target.ic_seekbar_content_thumb_bubble_text = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ic_seekbar_content_thumb_bubble_text, "field 'ic_seekbar_content_thumb_bubble_text'"), C0853R.C0855id.ic_seekbar_content_thumb_bubble_text, "field 'ic_seekbar_content_thumb_bubble_text'");
        target.tx_start_video_recording_resolution = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tx_start_video_recording_resolution, "field 'tx_start_video_recording_resolution'"), C0853R.C0855id.tx_start_video_recording_resolution, "field 'tx_start_video_recording_resolution'");
        target.tx_start_video_recording_fps = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tx_start_video_recording_fps, "field 'tx_start_video_recording_fps'"), C0853R.C0855id.tx_start_video_recording_fps, "field 'tx_start_video_recording_fps'");
        target.ll_start_video_recording_resolution_fps = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_start_video_recording_resolution_fps, "field 'll_start_video_recording_resolution_fps'"), C0853R.C0855id.ll_start_video_recording_resolution_fps, "field 'll_start_video_recording_resolution_fps'");
        target.ll_mark_point_a = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_mark_point_a, "field 'll_mark_point_a'"), C0853R.C0855id.ll_mark_point_a, "field 'll_mark_point_a'");
        target.ll_mark_point_b = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_mark_point_b, "field 'll_mark_point_b'"), C0853R.C0855id.ll_mark_point_b, "field 'll_mark_point_b'");
        target.ll_mark_point = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_mark_point, "field 'll_mark_point'"), C0853R.C0855id.ll_mark_point, "field 'll_mark_point'");
        target.iv_mark_quit_out = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_mark_quit_out, "field 'iv_mark_quit_out'"), C0853R.C0855id.iv_mark_quit_out, "field 'iv_mark_quit_out'");
        target.iv_mark_setting_menu = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_mark_setting_menu, "field 'iv_mark_setting_menu'"), C0853R.C0855id.iv_mark_setting_menu, "field 'iv_mark_setting_menu'");
        target.ll_mark_point_a_vertical = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_mark_point_a_vertical, "field 'll_mark_point_a_vertical'"), C0853R.C0855id.ll_mark_point_a_vertical, "field 'll_mark_point_a_vertical'");
        target.ll_mark_point_b_vertical = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_mark_point_b_vertical, "field 'll_mark_point_b_vertical'"), C0853R.C0855id.ll_mark_point_b_vertical, "field 'll_mark_point_b_vertical'");
        target.ll_mark_point_vertical = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_mark_point_vertical, "field 'll_mark_point_vertical'"), C0853R.C0855id.ll_mark_point_vertical, "field 'll_mark_point_vertical'");
        target.iv_mark_quit_out_vertical = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_mark_quit_out_vertical, "field 'iv_mark_quit_out_vertical'"), C0853R.C0855id.iv_mark_quit_out_vertical, "field 'iv_mark_quit_out_vertical'");
        target.iv_mark_setting_menu_vertical = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_mark_setting_menu_vertical, "field 'iv_mark_setting_menu_vertical'"), C0853R.C0855id.iv_mark_setting_menu_vertical, "field 'iv_mark_setting_menu_vertical'");
        target.ll_setting_x_mf = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_setting_x_mf, "field 'll_setting_x_mf'"), C0853R.C0855id.ll_setting_x_mf, "field 'll_setting_x_mf'");
        target.ll_setting_x_mf_value = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_setting_x_mf_value, "field 'll_setting_x_mf_value'"), C0853R.C0855id.ll_setting_x_mf_value, "field 'll_setting_x_mf_value'");
        target.tv_setting_x_point_location_a = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_setting_x_point_location_a, "field 'tv_setting_x_point_location_a'"), C0853R.C0855id.tv_setting_x_point_location_a, "field 'tv_setting_x_point_location_a'");
        target.tv_setting_x_point_location_b = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_setting_x_point_location_b, "field 'tv_setting_x_point_location_b'"), C0853R.C0855id.tv_setting_x_point_location_b, "field 'tv_setting_x_point_location_b'");
        target.ll_seekbar_inside_down = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_seekbar_inside_down, "field 'll_seekbar_inside_down'"), C0853R.C0855id.ll_seekbar_inside_down, "field 'll_seekbar_inside_down'");
        target.iv_gradienter_white = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_gradienter_white, "field 'iv_gradienter_white'"), C0853R.C0855id.iv_gradienter_white, "field 'iv_gradienter_white'");
        target.iv_gradienter_bg = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.iv_gradienter_bg, "field 'iv_gradienter_bg'"), C0853R.C0855id.iv_gradienter_bg, "field 'iv_gradienter_bg'");
    }

    public void unbind(T target) {
        target.iconGriding = null;
        target.llSeekbar = null;
        target.llSeekbarInside = null;
        target.tvTimer = null;
        target.btnManualFocus = null;
        target.rlFocus = null;
        target.contentLayout = null;
        target.content_layout_scale = null;
        target.content_layout_parameter_display = null;
        target.timer = null;
        target.timer_size_all = null;
        target.timer_size_all_view = null;
        target.timer_horizontal = null;
        target.timer_size_all_horizontal = null;
        target.timer_size_all_view_horizontal = null;
        target.timer_video_record_start_linear_horizontal = null;
        target.timer_video_record_start_linear = null;
        target.llFullShot = null;
        target.iconFullShot = null;
        target.btnFullShotCancel = null;
        target.rlPhotoSynthesis = null;
        target.pbSynthesis = null;
        target.fragment_content_two_ll = null;
        target.rlBright = null;
        target.rlBright2 = null;
        target.seekbarBrightness2 = null;
        target.seekbar_brightness2_view = null;
        target.seekbar_brightness_view = null;
        target.linear_timer = null;
        target.chro_timer = null;
        target.chro_all_timer = null;
        target.linear_timer_progress_bar = null;
        target.linear_timer_progress_recycler = null;
        target.tv_chro_all_timer_center = null;
        target.rl_timer_progress_bar = null;
        target.rl_focus_relative = null;
        target.ic_seekbar_content_thumb_bubble_text = null;
        target.tx_start_video_recording_resolution = null;
        target.tx_start_video_recording_fps = null;
        target.ll_start_video_recording_resolution_fps = null;
        target.ll_mark_point_a = null;
        target.ll_mark_point_b = null;
        target.ll_mark_point = null;
        target.iv_mark_quit_out = null;
        target.iv_mark_setting_menu = null;
        target.ll_mark_point_a_vertical = null;
        target.ll_mark_point_b_vertical = null;
        target.ll_mark_point_vertical = null;
        target.iv_mark_quit_out_vertical = null;
        target.iv_mark_setting_menu_vertical = null;
        target.ll_setting_x_mf = null;
        target.ll_setting_x_mf_value = null;
        target.tv_setting_x_point_location_a = null;
        target.tv_setting_x_point_location_b = null;
        target.ll_seekbar_inside_down = null;
        target.iv_gradienter_white = null;
        target.iv_gradienter_bg = null;
    }
}
