package p010me.iwf.photopicker.widget.control;

/* renamed from: me.iwf.photopicker.widget.control.IssueKey */
public enum IssueKey {
    LOOK_VIDEO_TOP_BUTTOM,
    LOOK_PHOTO_TOP_BUTTOM,
    VIDEO_PHOTO_CAMERA_DELETE_CHECK_HAVA,
    VIDEO_PHOTO_CAMERA_DELETE_CHECK_HAVA_NONE,
    VIDEO_PHOTO_CAMERA_DELETE_END,
    VIDEO_PHOTO_DELETE_END,
    VIDEO_PHOTO_HAVE_OR_NONE,
    VIDEO_SELECT_CHECK,
    PHOTO_VIDEO_CAMERA_DEIETE,
    PHOTO_VIDEO_DEIETE,
    VIDEO_PLAY,
    PHOTO_CHECK,
    CAMERA_CHECK,
    PHOTO_CHECK_OK,
    CAMERA_CHECK_OK,
    PHOTO_CHECK_LOOK,
    CAMERA_CHECK_LOOK,
    PHOTO_CHECK_ALL,
    CAMERA_CHECK_ALL,
    VIDEO_CHECK_ALL,
    CAMERA_VIDEO_CHECK_ALL,
    LOGIN_OK,
    DOWNLOAD_COMPLETED,
    INPUT_METHOD_CLOSED,
    INPUT_METHOD_OPENED
}
