package com.freevisiontech.fvmobile.activity;

import android.support.p003v7.widget.RecyclerView;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import android.widget.TextView;
import butterknife.ButterKnife;
import com.freevisiontech.fvmobile.C0853R;
import com.freevisiontech.fvmobile.activity.FVKcfFreestyleActivity;

public class FVKcfFreestyleActivity$$ViewBinder<T extends FVKcfFreestyleActivity> implements ButterKnife.ViewBinder<T> {
    public void bind(ButterKnife.Finder finder, T target, Object source) {
        target.btnExit = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.btn_Exit, "field 'btnExit'"), C0853R.C0855id.btn_Exit, "field 'btnExit'");
        target.tvNumber = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_number, "field 'tvNumber'"), C0853R.C0855id.tv_number, "field 'tvNumber'");
        target.icon1 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon1, "field 'icon1'"), C0853R.C0855id.icon1, "field 'icon1'");
        target.icon2 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon2, "field 'icon2'"), C0853R.C0855id.icon2, "field 'icon2'");
        target.icon3 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon3, "field 'icon3'"), C0853R.C0855id.icon3, "field 'icon3'");
        target.icon4 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon4, "field 'icon4'"), C0853R.C0855id.icon4, "field 'icon4'");
        target.icon5 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon5, "field 'icon5'"), C0853R.C0855id.icon5, "field 'icon5'");
        target.icon6 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon6, "field 'icon6'"), C0853R.C0855id.icon6, "field 'icon6'");
        target.icon7 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon7, "field 'icon7'"), C0853R.C0855id.icon7, "field 'icon7'");
        target.icon8 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon8, "field 'icon8'"), C0853R.C0855id.icon8, "field 'icon8'");
        target.icon9 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon9, "field 'icon9'"), C0853R.C0855id.icon9, "field 'icon9'");
        target.icon10 = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon10, "field 'icon10'"), C0853R.C0855id.icon10, "field 'icon10'");
        target.icon1_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon1_end, "field 'icon1_end'"), C0853R.C0855id.icon1_end, "field 'icon1_end'");
        target.icon2_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon2_end, "field 'icon2_end'"), C0853R.C0855id.icon2_end, "field 'icon2_end'");
        target.icon3_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon3_end, "field 'icon3_end'"), C0853R.C0855id.icon3_end, "field 'icon3_end'");
        target.icon4_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon4_end, "field 'icon4_end'"), C0853R.C0855id.icon4_end, "field 'icon4_end'");
        target.icon5_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon5_end, "field 'icon5_end'"), C0853R.C0855id.icon5_end, "field 'icon5_end'");
        target.icon6_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon6_end, "field 'icon6_end'"), C0853R.C0855id.icon6_end, "field 'icon6_end'");
        target.icon7_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon7_end, "field 'icon7_end'"), C0853R.C0855id.icon7_end, "field 'icon7_end'");
        target.icon8_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon8_end, "field 'icon8_end'"), C0853R.C0855id.icon8_end, "field 'icon8_end'");
        target.icon9_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon9_end, "field 'icon9_end'"), C0853R.C0855id.icon9_end, "field 'icon9_end'");
        target.icon10_end = (ImageView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.icon10_end, "field 'icon10_end'"), C0853R.C0855id.icon10_end, "field 'icon10_end'");
        target.ll_layout1_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout1_start, "field 'll_layout1_start'"), C0853R.C0855id.ll_layout1_start, "field 'll_layout1_start'");
        target.ll_layout2_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout2_start, "field 'll_layout2_start'"), C0853R.C0855id.ll_layout2_start, "field 'll_layout2_start'");
        target.ll_layout3_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout3_start, "field 'll_layout3_start'"), C0853R.C0855id.ll_layout3_start, "field 'll_layout3_start'");
        target.ll_layout4_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout4_start, "field 'll_layout4_start'"), C0853R.C0855id.ll_layout4_start, "field 'll_layout4_start'");
        target.ll_layout5_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout5_start, "field 'll_layout5_start'"), C0853R.C0855id.ll_layout5_start, "field 'll_layout5_start'");
        target.ll_layout6_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout6_start, "field 'll_layout6_start'"), C0853R.C0855id.ll_layout6_start, "field 'll_layout6_start'");
        target.ll_layout7_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout7_start, "field 'll_layout7_start'"), C0853R.C0855id.ll_layout7_start, "field 'll_layout7_start'");
        target.ll_layout8_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout8_start, "field 'll_layout8_start'"), C0853R.C0855id.ll_layout8_start, "field 'll_layout8_start'");
        target.ll_layout9_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout9_start, "field 'll_layout9_start'"), C0853R.C0855id.ll_layout9_start, "field 'll_layout9_start'");
        target.ll_layout10_start = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout10_start, "field 'll_layout10_start'"), C0853R.C0855id.ll_layout10_start, "field 'll_layout10_start'");
        target.ll_layout1_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout1_end, "field 'll_layout1_end'"), C0853R.C0855id.ll_layout1_end, "field 'll_layout1_end'");
        target.ll_layout2_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout2_end, "field 'll_layout2_end'"), C0853R.C0855id.ll_layout2_end, "field 'll_layout2_end'");
        target.ll_layout3_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout3_end, "field 'll_layout3_end'"), C0853R.C0855id.ll_layout3_end, "field 'll_layout3_end'");
        target.ll_layout4_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout4_end, "field 'll_layout4_end'"), C0853R.C0855id.ll_layout4_end, "field 'll_layout4_end'");
        target.ll_layout5_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout5_end, "field 'll_layout5_end'"), C0853R.C0855id.ll_layout5_end, "field 'll_layout5_end'");
        target.ll_layout6_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout6_end, "field 'll_layout6_end'"), C0853R.C0855id.ll_layout6_end, "field 'll_layout6_end'");
        target.ll_layout7_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout7_end, "field 'll_layout7_end'"), C0853R.C0855id.ll_layout7_end, "field 'll_layout7_end'");
        target.ll_layout8_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout8_end, "field 'll_layout8_end'"), C0853R.C0855id.ll_layout8_end, "field 'll_layout8_end'");
        target.ll_layout9_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout9_end, "field 'll_layout9_end'"), C0853R.C0855id.ll_layout9_end, "field 'll_layout9_end'");
        target.ll_layout10_end = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout10_end, "field 'll_layout10_end'"), C0853R.C0855id.ll_layout10_end, "field 'll_layout10_end'");
        target.ll_layout1 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout1, "field 'll_layout1'"), C0853R.C0855id.ll_layout1, "field 'll_layout1'");
        target.ll_layout2 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout2, "field 'll_layout2'"), C0853R.C0855id.ll_layout2, "field 'll_layout2'");
        target.ll_layout3 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout3, "field 'll_layout3'"), C0853R.C0855id.ll_layout3, "field 'll_layout3'");
        target.ll_layout4 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout4, "field 'll_layout4'"), C0853R.C0855id.ll_layout4, "field 'll_layout4'");
        target.ll_layout5 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout5, "field 'll_layout5'"), C0853R.C0855id.ll_layout5, "field 'll_layout5'");
        target.ll_layout6 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout6, "field 'll_layout6'"), C0853R.C0855id.ll_layout6, "field 'll_layout6'");
        target.ll_layout7 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout7, "field 'll_layout7'"), C0853R.C0855id.ll_layout7, "field 'll_layout7'");
        target.ll_layout8 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout8, "field 'll_layout8'"), C0853R.C0855id.ll_layout8, "field 'll_layout8'");
        target.ll_layout9 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout9, "field 'll_layout9'"), C0853R.C0855id.ll_layout9, "field 'll_layout9'");
        target.ll_layout10 = (RelativeLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.ll_layout10, "field 'll_layout10'"), C0853R.C0855id.ll_layout10, "field 'll_layout10'");
        target.tvHint = (TextView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.tv_hint, "field 'tvHint'"), C0853R.C0855id.tv_hint, "field 'tvHint'");
        target.act_fv_kcf_free_recycler_yyy = (RecyclerView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.act_fv_kcf_free_recycler_yyy, "field 'act_fv_kcf_free_recycler_yyy'"), C0853R.C0855id.act_fv_kcf_free_recycler_yyy, "field 'act_fv_kcf_free_recycler_yyy'");
        target.act_fv_kcf_free_recycler_linear_yyy = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.act_fv_kcf_free_recycler_linear_yyy, "field 'act_fv_kcf_free_recycler_linear_yyy'"), C0853R.C0855id.act_fv_kcf_free_recycler_linear_yyy, "field 'act_fv_kcf_free_recycler_linear_yyy'");
        target.act_fv_kcf_free_recycler_xxx = (RecyclerView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.act_fv_kcf_free_recycler_xxx, "field 'act_fv_kcf_free_recycler_xxx'"), C0853R.C0855id.act_fv_kcf_free_recycler_xxx, "field 'act_fv_kcf_free_recycler_xxx'");
        target.act_fv_kcf_free_recycler_linear_xxx = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.act_fv_kcf_free_recycler_linear_xxx, "field 'act_fv_kcf_free_recycler_linear_xxx'"), C0853R.C0855id.act_fv_kcf_free_recycler_linear_xxx, "field 'act_fv_kcf_free_recycler_linear_xxx'");
        target.act_fv_kcf_free_recycler_linear_scale_xxx = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.act_fv_kcf_free_recycler_linear_scale_xxx, "field 'act_fv_kcf_free_recycler_linear_scale_xxx'"), C0853R.C0855id.act_fv_kcf_free_recycler_linear_scale_xxx, "field 'act_fv_kcf_free_recycler_linear_scale_xxx'");
        target.act_fv_kcf_free_recycler_scale_xxx = (RecyclerView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.act_fv_kcf_free_recycler_scale_xxx, "field 'act_fv_kcf_free_recycler_scale_xxx'"), C0853R.C0855id.act_fv_kcf_free_recycler_scale_xxx, "field 'act_fv_kcf_free_recycler_scale_xxx'");
        target.act_fv_kcf_free_recycler_linear_scale_yyy = (LinearLayout) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.act_fv_kcf_free_recycler_linear_scale_yyy, "field 'act_fv_kcf_free_recycler_linear_scale_yyy'"), C0853R.C0855id.act_fv_kcf_free_recycler_linear_scale_yyy, "field 'act_fv_kcf_free_recycler_linear_scale_yyy'");
        target.act_fv_kcf_free_recycler_scale_yyy = (RecyclerView) finder.castView((View) finder.findRequiredView(source, C0853R.C0855id.act_fv_kcf_free_recycler_scale_yyy, "field 'act_fv_kcf_free_recycler_scale_yyy'"), C0853R.C0855id.act_fv_kcf_free_recycler_scale_yyy, "field 'act_fv_kcf_free_recycler_scale_yyy'");
    }

    public void unbind(T target) {
        target.btnExit = null;
        target.tvNumber = null;
        target.icon1 = null;
        target.icon2 = null;
        target.icon3 = null;
        target.icon4 = null;
        target.icon5 = null;
        target.icon6 = null;
        target.icon7 = null;
        target.icon8 = null;
        target.icon9 = null;
        target.icon10 = null;
        target.icon1_end = null;
        target.icon2_end = null;
        target.icon3_end = null;
        target.icon4_end = null;
        target.icon5_end = null;
        target.icon6_end = null;
        target.icon7_end = null;
        target.icon8_end = null;
        target.icon9_end = null;
        target.icon10_end = null;
        target.ll_layout1_start = null;
        target.ll_layout2_start = null;
        target.ll_layout3_start = null;
        target.ll_layout4_start = null;
        target.ll_layout5_start = null;
        target.ll_layout6_start = null;
        target.ll_layout7_start = null;
        target.ll_layout8_start = null;
        target.ll_layout9_start = null;
        target.ll_layout10_start = null;
        target.ll_layout1_end = null;
        target.ll_layout2_end = null;
        target.ll_layout3_end = null;
        target.ll_layout4_end = null;
        target.ll_layout5_end = null;
        target.ll_layout6_end = null;
        target.ll_layout7_end = null;
        target.ll_layout8_end = null;
        target.ll_layout9_end = null;
        target.ll_layout10_end = null;
        target.ll_layout1 = null;
        target.ll_layout2 = null;
        target.ll_layout3 = null;
        target.ll_layout4 = null;
        target.ll_layout5 = null;
        target.ll_layout6 = null;
        target.ll_layout7 = null;
        target.ll_layout8 = null;
        target.ll_layout9 = null;
        target.ll_layout10 = null;
        target.tvHint = null;
        target.act_fv_kcf_free_recycler_yyy = null;
        target.act_fv_kcf_free_recycler_linear_yyy = null;
        target.act_fv_kcf_free_recycler_xxx = null;
        target.act_fv_kcf_free_recycler_linear_xxx = null;
        target.act_fv_kcf_free_recycler_linear_scale_xxx = null;
        target.act_fv_kcf_free_recycler_scale_xxx = null;
        target.act_fv_kcf_free_recycler_linear_scale_yyy = null;
        target.act_fv_kcf_free_recycler_scale_yyy = null;
    }
}
